finish login with LinkedIn
Hacknocraft/HCSocialSignIn pull request #1
Opened 2017-06-07 08:14 UTC by Lebron1992

2017-06-07 14:04 UTC, laeroah commented on HCSocialSignIn/LandingViewController.swift
> +        linkedInManager = HCLinkedInManager(key: linkedInKey, secret: linkedInSecret, redirectUrl: redirectUrl)
I think we should define redirectURL as a constant. The user of the class should not worry about the redirect URL. 
Also, the linkedInManager should still be a singleton. There's no reason for the user to have to pass in the linkedin key and secret every time. The key and secret should be remembered by the shared instance.

2017-06-07 14:06 UTC, laeroah commented on Source/LinkedInWebViewController.swift
> +            if let code = urlParts.first?.components(separatedBy: "=")[1] {
this is a really unreliable way to get the URL params. It can potentially cause crash. Please use:
```
func getQueryStringParameter(url: String, param: String) -> String? {
  guard let url = URLComponents(string: url) else { return nil }
  return url.queryItems?.first(where: { $0.name == param })?.value
}
```

2017-06-07 14:09 UTC, laeroah commented on Source/LinkedInWebViewController.swift
> +        webView = UIWebView(frame: view.bounds)
Please use autolayout to do this. 
```
       let layoutViews: [String: Any] = ["view": self.view, "webview": webview]
        let horizontalConstraints = NSLayoutConstraint.constraints(
            withVisualFormat: "H:|-[segmentView]-|",
            options: NSLayoutFormatOptions.alignAllCenterY,
            metrics: nil, views: layoutViews)
        view.addConstraints(horizontalConstraints)

        let veriticalConstraints = NSLayoutConstraint.constraints(
            withVisualFormat: "V:|-[segmentView]-|",
            options: NSLayoutFormatOptions.alignAllCenterY,
            metrics: nil, views: layoutViews)
        view.addConstraints(veriticalConstraints)

```
![simulator screen shot jun 7 2017 10 02 25 am](https://user-images.githubusercontent.com/1928509/26882680-0991a7d4-4b69-11e7-948d-7293c580e0d5.png)

2017-06-07 14:10 UTC, laeroah commented on Source/LinkedInWebViewController.swift
>          self.redirectUrl = redirectUrl
You can add a redirectURL getter inside the LinkedInManager, so you don't need to pass it as a parameter here.

2017-06-07 14:11 UTC, laeroah requested changes
Please fix the review problems.

2017-06-07 15:53 UTC, Lebron1992 commented on HCSocialSignIn/LandingViewController.swift
> +        linkedInManager = HCLinkedInManager(key: linkedInKey, secret: linkedInSecret, redirectUrl: redirectUrl)
Yeah, the `redirectURL` is useless for the user, we can define it as a constant.

2017-06-07 15:54 UTC, Lebron1992 commented on Source/LinkedInWebViewController.swift
> +            if let code = urlParts.first?.components(separatedBy: "=")[1] {
ok

2017-06-07 15:57 UTC, Lebron1992 commented on Source/LinkedInWebViewController.swift
> +        webView = UIWebView(frame: view.bounds)
`webView = UIWebView(frame: view.bounds)` this can't make the `webView` cover the whole `view`?

2017-06-07 15:58 UTC, Lebron1992 commented on Source/LinkedInWebViewController.swift
>          self.redirectUrl = redirectUrl
ok

2017-06-07 16:03 UTC, laeroah commented on Source/LinkedInWebViewController.swift
> +        webView = UIWebView(frame: view.bounds)
no, in viewdidload, the view bounds are not decided yet.
You need to always use autolayout regardless. Your logic will have problem with device rotation and etc.

2017-06-08 01:24 UTC, laeroah approved these changes
cool. :shipit:

2017-06-08 01:34 UTC, merged